# Generated by Django 5.2.8 on 2025-11-09 09:57

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='Jamngeny Vision', max_length=200)),
                ('site_description', models.TextField(blank=True, default='ICT, Cybersecurity, and Strategic Writing Portfolio')),
                ('contact_email', models.EmailField(default='jamngeny@gmail.com', max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, default='Site is under maintenance. Please check back later.')),
                ('max_login_attempts', models.PositiveIntegerField(default=5)),
                ('login_timeout_minutes', models.PositiveIntegerField(default=30)),
                ('password_min_length', models.PositiveIntegerField(default=8)),
                ('require_password_complexity', models.BooleanField(default=True)),
                ('api_rate_limit', models.PositiveIntegerField(default=1000, help_text='Requests per hour per user')),
                ('cache_timeout', models.PositiveIntegerField(default=300, help_text='Cache timeout in seconds')),
                ('search_results_limit', models.PositiveIntegerField(default=50)),
                ('enable_registration', models.BooleanField(default=False)),
                ('enable_comments', models.BooleanField(default=False)),
                ('enable_newsletter', models.BooleanField(default=False)),
                ('enable_analytics', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('slack_notifications', models.BooleanField(default=False)),
                ('slack_webhook_url', models.URLField(blank=True)),
                ('auto_backup', models.BooleanField(default=False)),
                ('backup_frequency_days', models.PositiveIntegerField(default=7)),
                ('monitor_uptime', models.BooleanField(default=True)),
                ('theme_settings', models.JSONField(blank=True, default=dict, help_text='Theme customization settings')),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS code')),
                ('custom_js', models.TextField(blank=True, help_text='Custom JavaScript code')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional system metadata')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_type', models.CharField(choices=[('database', 'Database'), ('cache', 'Cache'), ('storage', 'Storage'), ('external_api', 'External API'), ('celery', 'Celery'), ('full', 'Full System')], max_length=50)),
                ('is_successful', models.BooleanField()),
                ('response_time', models.FloatField(help_text='Response time in milliseconds')),
                ('error_message', models.TextField(blank=True)),
                ('server_hostname', models.CharField(blank=True, max_length=200)),
                ('python_version', models.CharField(blank=True, max_length=50)),
                ('django_version', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['check_type', 'created_at'], name='utils_healt_check_t_42caf3_idx'), models.Index(fields=['is_successful', 'created_at'], name='utils_healt_is_succ_9680f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('is_authenticated', models.BooleanField(default=False)),
                ('status_code', models.PositiveIntegerField()),
                ('response_size', models.PositiveIntegerField(default=0, help_text='Response size in bytes')),
                ('response_time', models.FloatField(help_text='Response time in milliseconds')),
                ('error_message', models.TextField(blank=True)),
                ('exception_type', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Request Log',
                'verbose_name_plural': 'API Request Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['path', 'created_at'], name='utils_apire_path_b681ad_idx'), models.Index(fields=['method', 'created_at'], name='utils_apire_method_1d005f_idx'), models.Index(fields=['status_code', 'created_at'], name='utils_apire_status__f63b51_idx'), models.Index(fields=['user', 'created_at'], name='utils_apire_user_id_3a20ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('download', 'Download'), ('upload', 'Upload'), ('export', 'Export'), ('import', 'Import'), ('approve', 'Approve'), ('reject', 'Reject'), ('publish', 'Publish'), ('unpublish', 'Unpublish'), ('other', 'Other')], max_length=20)),
                ('entity', models.CharField(choices=[('user', 'User'), ('article', 'Article'), ('portfolio', 'Portfolio Item'), ('service', 'Service'), ('file', 'File'), ('contact_message', 'Contact Message'), ('tag', 'Tag'), ('category', 'Category'), ('system', 'System'), ('auth', 'Authentication'), ('api', 'API')], max_length=50)),
                ('entity_id', models.CharField(blank=True, help_text='ID of the affected entity', max_length=100)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Detailed action data (changes, parameters, etc.)')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Field-level changes (for update actions)')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('is_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the action was requested')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='utils_audit_search__30d9f1_gin'), models.Index(fields=['entity', 'entity_id'], name='utils_audit_entity_a71072_idx'), models.Index(fields=['action', 'created_at'], name='utils_audit_action_fb2f53_idx'), models.Index(fields=['performed_by', 'created_at'], name='utils_audit_perform_1cb927_idx'), models.Index(fields=['severity', 'created_at'], name='utils_audit_severit_1f2854_idx')],
            },
        ),
    ]
