# Generated by Django 5.2.8 on 2025-11-09 08:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the category')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Portfolio categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('summary', models.TextField(help_text='Brief summary/description')),
                ('content', models.TextField(blank=True, help_text='Detailed content (HTML allowed)')),
                ('sanitized_content', models.TextField(blank=True, editable=False)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='portfolio/featured/')),
                ('link', models.URLField(blank=True, help_text='External link to project/demo')),
                ('client', models.CharField(blank=True, help_text='Client name (if applicable)', max_length=200)),
                ('project_date', models.DateField(help_text='When the project was completed')),
                ('duration', models.CharField(blank=True, help_text='Project duration (e.g., 3 months)', max_length=50)),
                ('technologies', models.JSONField(blank=True, default=list, help_text='List of technologies used (stored as JSON array)')),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('meta_description', models.CharField(blank=True, help_text='SEO description', max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (stored as JSON object)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Main category for this portfolio item', on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_items', to='portfolio.portfoliocategory')),
                ('secondary_categories', models.ManyToManyField(blank=True, help_text='Additional categories for this item', related_name='secondary_portfolio_items', to='portfolio.portfoliocategory')),
            ],
            options={
                'ordering': ['-project_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='portfolio/images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_featured', models.BooleanField(default=False, help_text='Use as featured image for the item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.portfolioitem')),
            ],
            options={
                'ordering': ['portfolio_item', 'order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['is_published', 'is_featured', 'project_date'], name='portfolio_p_is_publ_d22cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['slug'], name='portfolio_p_slug_229a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['category'], name='portfolio_p_categor_f3d992_idx'),
        ),
    ]
