# Generated by Django 5.2.8 on 2025-11-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sanitized_content',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='Full article content (HTML allowed)'),
        ),
    ]
