# Generated by Django 5.2.8 on 2025-11-09 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_contact_form_enabled', models.BooleanField(default=True)),
                ('require_name', models.BooleanField(default=True)),
                ('require_email', models.BooleanField(default=True)),
                ('require_phone', models.BooleanField(default=False)),
                ('require_company', models.BooleanField(default=False)),
                ('require_subject', models.BooleanField(default=False)),
                ('rate_limit_enabled', models.BooleanField(default=True)),
                ('rate_limit_period', models.PositiveIntegerField(default=3600, help_text='Rate limit period in seconds')),
                ('rate_limit_count', models.PositiveIntegerField(default=5, help_text='Maximum number of messages per period')),
                ('notify_on_new_message', models.BooleanField(default=True)),
                ('notification_emails', models.TextField(blank=True, help_text='Comma-separated list of email addresses to notify')),
                ('auto_response_enabled', models.BooleanField(default=True)),
                ('auto_response_subject', models.CharField(blank=True, max_length=200)),
                ('auto_response_message', models.TextField(blank=True)),
                ('recaptcha_enabled', models.BooleanField(default=False)),
                ('recaptcha_site_key', models.CharField(blank=True, max_length=100)),
                ('recaptcha_secret_key', models.CharField(blank=True, max_length=100)),
                ('available_categories', models.JSONField(blank=True, default=list, help_text='Available contact categories as JSON array')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Settings',
                'verbose_name_plural': 'Contact Settings',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, help_text='Company/organization name', max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(blank=True, help_text="Message category (e.g., 'consulting', 'writing', 'general')", max_length=50)),
                ('source', models.CharField(choices=[('website', 'Website Form'), ('api', 'API'), ('admin', 'Admin Panel'), ('email', 'Email'), ('other', 'Other')], default='website', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived'), ('spam', 'Spam')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('is_processed', models.BooleanField(default=False)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes for team members')),
                ('response_sent', models.BooleanField(default=False)),
                ('response_notes', models.TextField(blank=True, help_text='Notes about the response sent')),
                ('response_sent_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, help_text='HTTP referrer if available')),
                ('consent_given', models.BooleanField(default=True, help_text='User consent for data processing')),
                ('newsletter_subscribed', models.BooleanField(default=False, help_text='User subscribed to newsletter')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (form fields, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Team member assigned to handle this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='contact_con_status_402fcf_idx'), models.Index(fields=['email', 'created_at'], name='contact_con_email_02ea8f_idx'), models.Index(fields=['source', 'created_at'], name='contact_con_source_ed6325_idx'), models.Index(fields=['is_processed', 'created_at'], name='contact_con_is_proc_59f7c9_idx')],
            },
        ),
    ]
