# Generated by Django 5.2.8 on 2025-11-09 09:57

import django.db.models.deletion
import files.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to=files.models.file_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('file_extension', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('pdf', 'PDF'), ('archive', 'Archive'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Display title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='File description')),
                ('alt_text', models.TextField(blank=True, help_text='Alternative text for images')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional file metadata')),
                ('is_public', models.BooleanField(default=False, help_text='Publicly accessible without authentication')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True, help_text='File has been approved for use')),
                ('virus_scan_status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Error')], default='pending', max_length=20)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileUploadRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('file_extension', models.CharField(max_length=10)),
                ('upload_token', models.CharField(max_length=100, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('purpose', models.CharField(blank=True, help_text='Purpose of this upload', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resulting_file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_request', to='files.file')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['category', 'is_public', 'is_approved'], name='files_file_categor_eca06b_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='files_file_uploade_abf04e_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['mime_type'], name='files_file_mime_ty_57dbdc_idx'),
        ),
    ]
