# Generated by Django 5.2.8 on 2025-11-09 09:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name', max_length=200)),
                ('title', models.CharField(help_text='Professional title/headline', max_length=200)),
                ('bio', models.TextField(help_text='Detailed biography (HTML allowed)')),
                ('sanitized_bio', models.TextField(blank=True, editable=False)),
                ('photo', models.ImageField(blank=True, help_text='Professional portrait', null=True, upload_to='about/')),
                ('profile_pdf', models.FileField(blank=True, help_text='Downloadable PDF profile', null=True, upload_to='about/documents/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('social_links', models.JSONField(blank=True, default=dict, help_text="Social media links as JSON: {'linkedin': 'url', 'twitter': 'url', ...}")),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of professional experience')),
                ('projects_completed', models.PositiveIntegerField(default=0, help_text='Number of projects completed')),
                ('clients_served', models.PositiveIntegerField(default=0, help_text='Number of clients served')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (max 60 chars)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (max 160 chars)', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(help_text='Detailed service description')),
                ('short_description', models.CharField(blank=True, help_text='Brief description for cards and listings', max_length=300)),
                ('icon_name', models.CharField(blank=True, help_text="Icon name (e.g., 'shield', 'code', 'writing', 'strategy')", max_length=50)),
                ('icon_color', models.CharField(default='#6366F1', help_text='Hex color for the icon (e.g., #6366F1)', max_length=7)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('image', models.ImageField(blank=True, help_text='Service image/illustration', null=True, upload_to='services/')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of key features for this service')),
                ('starting_price', models.DecimalField(blank=True, decimal_places=2, help_text='Starting price (optional)', max_digits=10, null=True)),
                ('price_unit', models.CharField(blank=True, default='project', help_text="Price unit (e.g., 'project', 'hour', 'month')", max_length=20)),
                ('cta_text', models.CharField(default='Learn More', help_text='Call-to-action button text', max_length=50)),
                ('cta_link', models.CharField(blank=True, help_text='CTA link (relative URL or full URL)', max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured services section')),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
